### PR TITLE
Notebook for single DMP and dmp notebooks setup files

### PR DESCRIPTION
**Pull request by kjgarza**
## Purpose

Added notebooks to address the use cases of:

Notebook 1: Show everything that is connected to a single DMP. This demonstrates the vision of a DMP as a container for a research project.
Datasets (DOI)
Funding (DOI)
People (ORCID)
Organizations (RoR)

image

closes: https://github.com/datacite/datacite/issues/1080

further details: https://docs.google.com/document/d/1LRP8GbyO-z1I4fjmvb4dsnsHzayJR3TxvpDcjP32iis/edit#
https://docs.google.com/document/d/1LMuqAHe5y6cXPJQYT7X7vmspo0o5KhTt5Nyy_yYz5Tw/edit#

## Approach
- using vega specs for the visulisation

## Learning

- one needs to use altair library in jupyter to use vega.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)

- [x] New feature (non-breaking change which adds functionality)

- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Reviewer, please remember our [guidelines](https://datacite.atlassian.net/wiki/spaces/TEC/pages/1168375809/Pull+Request+Guidelines):

- Be humble in the language and feedback you give, ask don't tell.
- Consider using positive language as opposed to neutral when offering feedback. This is to avoid the negative bias that can occur with neutral language appearing negative.
- Offer suggestions on how to improve code e.g. simplification or expanding clarity.
- Ensure you give reasons for the changes you are proposing.

### CODE REVIEW

**Comment by kjgarza** [comment]
@mfenner I added the first version of the maDMP for the single DMP. 
There is a sample of the queries I am specking to be able to do to graphQL to get the queries in both notebooks. Please do take a look.

**Comment by kjgarza** [comment]
By the way is the first use of the **DRAFT PR** requests  and the **new PR template** as we agreed in the Virtual Dev Meeting

**Comment by mfenner** [comment]
@kjgarza what is it that I should review? Is it a working notebook and I should check that it is working as expected? Or is there a specific aspect you want feedback on?

**Comment by kjgarza** [comment]
@mfenner well I don't know how you review notebooks. But i guess whether we can considered closed? 
specifically notebook `dmp/user-story-single-dmp-connections.ipynb` is the one needs to be reviewed. Should I add Sarala in the review? I actually didn't' thought about that

**Review by mfenner — APPROVED** [review]
LGTM for now

**Pull request merged**
